name: module-py

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
  schedule:
    - cron: "0 7 * * 2"

concurrency: this

env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
  MONGODB_ATLAS_ORG: ${{ secrets.MONGODB_ATLAS_ORG }}
  SLACK_URL: ${{ secrets.SLACK_URL }}

defaults:
  run:
    shell: bash
    working-directory: test/src

jobs:
  module-py:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - uses: hashicorp/setup-terraform@v2.0.3 # https://github.com/hashicorp/setup-terraform/releases
        with:
          terraform_version: 1.3.5 # https://github.com/hashicorp/terraform/releases
          terraform_wrapper: false

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install python libs
        shell: bash
        run: cd test/src && pip3 install -r requirements.txt
      - name: tftest
        shell: bash
        run: |
          cd test/src && python examples_test.py
